server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Necessário para Single Page Applications (SPA) como React/Vite
    # Garante que as rotas feitas no frontend não retornem erro 404
    location / {
        try_files $uri $uri/ /index.html;
    }
}
